import {
  FaSchool,
  FaUserGraduate,
  FaChalkboardTeacher,
  FaMoneyBillWave,
  FaUserPlus,
  FaClipboardCheck,
  FaBell,
  FaRegistered,
  FaIdCard,
  FaEnvelope,
  FaPhoneAlt,
  FaMapMarkerAlt,
  FaListUl,
  FaImage,
  FaHeading,
  FaPlus,
  FaList,
  FaChalkboard,
  FaLayerGroup,
  FaUserTie,
  FaDoorOpen,
  FaUsers,
  FaUser,
  
  FaQuestionCircle,
} from "react-icons/fa";

import { PiUserListBold } from "react-icons/pi";
import {
  FiArrowUpRight,
  FiMoreHorizontal,
  FiTrendingUp,
  FiSearch,
  FiPlus,
  FiEdit2,
  FiTrash2,
  FiEye,
  FiUsers,
  FiCalendar,
  FiBarChart2,
  FiHome,
  FiMoreVertical,
  FiChevronRight,
  FiChevronLeft
} from "react-icons/fi";
import { BiSolidSchool } from "react-icons/bi";
import { SiGoogleclassroom } from "react-icons/si";
import { PiStudent } from "react-icons/pi";

const icons = {
  FaQuestionCircle,
  FaSchool,
  FiMoreVertical,
  FaUserGraduate,
  FaChalkboardTeacher,
  FaMoneyBillWave,
  FaUserPlus,
  BiSolidSchool,
  FaClipboardCheck,
  FaBell,
  FaRegistered,
  FiBarChart2,
  FiCalendar,
  FiHome,
  FiChevronRight,
  FiChevronLeft,

  FaIdCard,
  FaEnvelope,
  FaPhoneAlt,
  FaMapMarkerAlt,
  PiUserListBold,
  FaListUl,
  FaImage,
  FiUsers,
  FaHeading,
  FaPlus,
  FaList,
  FiArrowUpRight,
  FiMoreHorizontal,
  FiTrendingUp,
  SiGoogleclassroom,
  FiSearch,
  FiPlus,
  FiEdit2,
  FiTrash2,
  FiEye,
  FaChalkboard,
  FaLayerGroup,
  FaUserTie,
  FaDoorOpen,
  FaUsers,
  FaUser,
  PiStudent
};

export default icons;
